language: go
go:
    - 1.5.2

sudo: required
services:
    - docker

install:
    - "sudo apt-get update && sudo apt-get install -y python-virtualenv"
script:
    - "sudo pip install tox"
    - "make dependencies build"
    - "./slappy -h || true"
    - "cd tests && SLAPPY_EXE=../slappy make start-containers write-test-config && tox"

notifications:
    email: false
