language: go
go:
    - 1.5.2

sudo: required
services:
    - docker

install:
    - "sudo apt-get update && sudo apt-get install -y python-virtualenv"
script:
    - "make dependencies build"
    - "./slappy -h || true"
    - "SLAPPY_EXE=../slappy make test"

notifications:
    email: false
